services:
  - type: web
    name: mass-report-bot
    env: python
    region: oregon # Region rapidă
    plan: free # Sau starter dacă vrei CPU dedicat constant
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: SERVER_ID
        sync: false
    autoDeploy: true
